[package]
name = "xreflect-proc-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "2.0.72"
xreflect-core = { path = "../xreflect-core" }
phf = "0.11.2"